# Generated by Django 4.2.7 on 2023-11-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='real_user',
            field=models.BooleanField(default=True),
        ),
    ]
