# Generated by Django 4.2.7 on 2023-11-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='quiz_marks',
            field=models.IntegerField(default=0),
        ),
    ]
